INSERT INTO product (category, brand, model) VALUES
('laptop', 'Toshiba', 'X1'),
('laptop', 'Asus', 'Vivobook 14'),
('laptop', 'Acer', 'Aspire 5'),
('laptop', 'Lenovo', 'ThinkPad E14'),
('laptop', 'HP', 'Pavilion 15'),
('computer', 'Dell', 'OptiPlex 7090'),
('computer', 'HP', 'EliteDesk 800'),
('computer', 'Lenovo', 'ThinkCentre M70'),
('computer', 'Acer', 'Veriton X'),
('computer', 'Asus', 'ExpertCenter D5'),
('desktop', 'Dell', 'Inspiron Desktop'),
('desktop', 'HP', 'Slim Desktop S01'),
('desktop', 'Lenovo', 'IdeaCentre 3'),
('desktop', 'Acer', 'Aspire TC'),
('desktop', 'Asus', 'ROG Strix G10'),
('all in one', 'Apple', 'iMac 24'),
('all in one', 'HP', 'All-in-One 22'),
('all in one', 'Lenovo', 'IdeaCentre AIO 3'),
('all in one', 'Dell', 'Inspiron AIO 24'),
('all in one', 'Acer', 'Aspire C27'),
('phone', 'Apple', 'iPhone 13'),
('phone', 'Samsung', 'Galaxy S21'),
('phone', 'Xiaomi', 'Redmi Note 11'),
('phone', 'Oppo', 'Reno 8'),
('phone', 'Vivo', 'V25'),
('tablet', 'Apple', 'iPad Air'),
('tablet', 'Samsung', 'Galaxy Tab S8'),
('tablet', 'Huawei', 'MatePad 11'),
('tablet', 'Lenovo', 'Tab P11'),
('tablet', 'Xiaomi', 'Pad 5'),
('smart band', 'Xiaomi', 'Mi Band 7'),
('smart band', 'Huawei', 'Band 8'),
('smart band', 'Honor', 'Band 6'),
('smart band', 'Amazfit', 'Band 5'),
('smart band', 'Samsung', 'Galaxy Fit 2'),
('smart watch', 'Apple', 'Watch Series 8'),
('smart watch', 'Samsung', 'Galaxy Watch 5'),
('smart watch', 'Garmin', 'Venu Sq'),
('smart watch', 'Huawei', 'Watch GT 3'),
('smart watch', 'Amazfit', 'GTR 4'),
('smart ring', 'Oura', 'Ring Gen3'),
('smart ring', 'Ultrahuman', 'Ring Air'),
('smart ring', 'Movano', 'Evie Ring'),
('smart ring', 'RingConn', 'Smart Ring'),
('smart ring', 'Circular', 'Ring Pro');