INSERT INTO product (category, brand, model) VALUES
('tablet', 'Huawei', 'MatePad 11'),
('laptop', 'HP', 'Pavilion 15'),
('smart watch', 'Garmin', 'Venu Sq'),
('computer', 'Lenovo', 'ThinkCentre M70'),
('smart ring', 'Circular', 'Ring Pro'),
('phone', 'Samsung', 'Galaxy S21'),
('desktop', 'Acer', 'Aspire TC'),
('all in one', 'Dell', 'Inspiron AIO 24'),
('smart band', 'Honor', 'Band 6'),
('tablet', 'Apple', 'iPad Air'),
('computer', 'Acer', 'Veriton X'),
('smart ring', 'Ultrahuman', 'Ring Air'),
('desktop', 'HP', 'Slim Desktop S01'),
('laptop', 'Lenovo', 'ThinkPad E14'),
('phone', 'Oppo', 'Reno 8'),
('smart watch', 'Huawei', 'Watch GT 3'),
('smart band', 'Samsung', 'Galaxy Fit 2'),
('all in one', 'Acer', 'Aspire C27'),
('desktop', 'Lenovo', 'IdeaCentre 3'),
('tablet', 'Lenovo', 'Tab P11'),
('computer', 'Dell', 'OptiPlex 7090'),
('smart ring', 'Oura', 'Ring Gen3'),
('laptop', 'Asus', 'Vivobook 14'),
('phone', 'Apple', 'iPhone 13'),
('smart watch', 'Apple', 'Watch Series 8'),
('smart band', 'Huawei', 'Band 8'),
('desktop', 'Asus', 'ROG Strix G10'),
('all in one', 'Apple', 'iMac 24'),
('tablet', 'Samsung', 'Galaxy Tab S8'),
('smart watch', 'Samsung', 'Galaxy Watch 5'),
('computer', 'HP', 'EliteDesk 800'),
('laptop', 'Acer', 'Aspire 5'),
('smart band', 'Xiaomi', 'Mi Band 7'),
('all in one', 'HP', 'All-in-One 22'),
('phone', 'Xiaomi', 'Redmi Note 11'),
('desktop', 'Dell', 'Inspiron Desktop'),
('tablet', 'Xiaomi', 'Pad 5'),
('smart ring', 'RingConn', 'Smart Ring'),
('computer', 'Asus', 'ExpertCenter D5'),
('all in one', 'Lenovo', 'IdeaCentre AIO 3'),
('laptop', 'Toshiba', 'X1'),
('phone', 'Vivo', 'V25'),
('smart band', 'Amazfit', 'Band 5'),
('smart watch', 'Amazfit', 'GTR 4'),
('smart ring', 'Movano', 'Evie Ring');
